CREATE TABLE IF NOT EXISTS renta_cancha.cliente_token_gestion (
    id_token_gestion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NOT NULL REFERENCES renta_cancha.cliente(id_cliente) ON DELETE CASCADE,
    token_hash VARCHAR(64) NOT NULL UNIQUE
);

CREATE INDEX IF NOT EXISTS idx_cliente_token_gestion_id_cliente
    ON renta_cancha.cliente_token_gestion (id_cliente);
